<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_United States</name>
   <tag></tag>
   <elementGuidId>e9870d6c-2194-4760-a9f9-62982dec37f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icp-touch-link-country</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-touch-link-country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de67f2f1-0e9b-41cf-a853-b2db363d734b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/customer-preferences/country?ie=UTF8&amp;preferencesReturnUrl=%2F&amp;ref_=footer_icp_cp</value>
      <webElementGuid>1534aa97-530a-42d8-a155-694f8ceaca4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Choose a country/region for shopping.</value>
      <webElementGuid>b464ce22-101d-4d25-95d8-2e7b0b711419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icp-button</value>
      <webElementGuid>0e91dd4c-1611-43a1-909b-6e74609c0de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icp-touch-link-country</value>
      <webElementGuid>9845f68c-11c4-439f-8731-a680ff41c7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  United States
</value>
      <webElementGuid>baabb6f5-d248-442f-95f1-544158e48aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-touch-link-country&quot;)</value>
      <webElementGuid>890d7fa8-b551-4d5b-bae2-c4f90dc791eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='icp-touch-link-country']</value>
      <webElementGuid>467bf5c4-3b2a-4c86-8e06-89f52e94ca6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[3]/span[2]/div/a[3]</value>
      <webElementGuid>941b3cf7-cd5a-41ed-bb2f-4c242015cf9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/customer-preferences/country?ie=UTF8&amp;preferencesReturnUrl=%2F&amp;ref_=footer_icp_cp')]</value>
      <webElementGuid>069a1847-2935-4cce-97be-8a659d450894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a[3]</value>
      <webElementGuid>9a152da9-3911-4fb0-81d1-5f07903265d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/customer-preferences/country?ie=UTF8&amp;preferencesReturnUrl=%2F&amp;ref_=footer_icp_cp' and @id = 'icp-touch-link-country' and (text() = '
  United States
' or . = '
  United States
')]</value>
      <webElementGuid>b58f5cec-eeb6-4a48-b168-2f689fd2fb64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
