<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_United States</name>
   <tag></tag>
   <elementGuidId>b6a639c1-7970-4373-869f-8b511bd0485c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-button-text.a-declarative</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='icp-dropdown']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b44c7a28-d786-4952-be15-ebd8562980a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text a-declarative</value>
      <webElementGuid>bf593b84-0955-4476-a4f6-cf7e43953fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-func-deps</name>
      <type>Main</type>
      <value>aui-da-a-dropdown-button</value>
      <webElementGuid>fe9e6467-1171-43f9-b92f-26406c6a9e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>6fef588f-76d3-4fd5-92b5-0d678bbe4524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>5b2ed967-c7a5-45ee-9b3b-0c3bf5ea21bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-button</value>
      <webElementGuid>4c2586a4-a204-440f-94a5-6fa027200095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32acfeef-9d33-4b02-9557-17be8437fe1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>5o5vk2-riqksc-ug2tvt-2098np</value>
      <webElementGuid>0382eb09-0a3f-4366-9569-23d85c3d5e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    United States
                            </value>
      <webElementGuid>1cb458f4-a3c8-4beb-976a-db1382bf5145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-page&quot;)/div[@class=&quot;a-container&quot;]/div[@class=&quot;a-row a-spacing-extra-large a-spacing-top-base a-ws-row&quot;]/div[@class=&quot;a-column a-span12 a-ws-span10 a-ws-spacing-none&quot;]/div[@class=&quot;a-row a-ws-row&quot;]/div[@class=&quot;a-column a-span12 a-ws-span7&quot;]/span[@class=&quot;a-dropdown-container&quot;]/span[@id=&quot;icp-dropdown&quot;]/span[@class=&quot;a-button-inner&quot;]/span[@class=&quot;a-button-text a-declarative&quot;]</value>
      <webElementGuid>0d926019-1dee-4083-a003-8e31fa7349cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='icp-dropdown']/span/span</value>
      <webElementGuid>1e82df3a-79d7-4fce-ac93-f8b2f22a3a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>cd5ad6ec-b993-49a3-8c11-25f241af69c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                    United States
                            ' or . = '
                                    United States
                            ')]</value>
      <webElementGuid>ca30be97-b12a-48f1-962f-ffb6363016da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
