<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>c46700ad-45f4-45bf-b3e0-374574cd137f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ap_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ap_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88272a2f-4988-4bab-9dcb-e9a2d6e29a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f7fa8734-27ef-44b9-9818-a6b3026ab36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>4ce22f26-d3aa-4b2c-96cd-bd7dfd418b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap_email</value>
      <webElementGuid>f9d16eae-aa22-4c45-aa96-5b53ab9e3f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9e7c5dd0-566b-40f3-88d4-688ab7e32f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7b5bf238-0605-408e-9d4d-d8cdc9cf3306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12 auth-autofocus auth-required-field</value>
      <webElementGuid>b334c1b8-471f-41ab-be6f-d64e1fa4b62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_email&quot;)</value>
      <webElementGuid>77776e37-709c-45ae-9d63-92fb8e25b106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ap_email']</value>
      <webElementGuid>c0a46e46-1f7c-472e-bc54-f4aa4c7e83ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authportal-main-section']/div[2]/div[2]/div/form/div/div/div/div/input</value>
      <webElementGuid>12384e5b-bb73-4ff3-82a9-2be772c62af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>99fdfb1e-3994-427d-b91a-711e7717ab7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'ap_email' and @name = 'email']</value>
      <webElementGuid>f97de3a3-4395-471e-9713-1a57a61a8d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
