<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_nav-sprite hmenu-close-icon</name>
   <tag></tag>
   <elementGuidId>3e4bba3b-675e-4511-aa7e-fee30c028a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.nav-sprite.hmenu-close-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-canvas-background']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c555f277-7b53-46c4-b6e5-c237bed34c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-sprite hmenu-close-icon</value>
      <webElementGuid>0b4ff2d5-8404-4f42-9f6b-2f503f8fcb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;a-js a-audio a-video a-canvas a-svg a-drag-drop a-geolocation a-history a-webworker a-autofocus a-input-placeholder a-textarea-placeholder a-local-storage a-gradients a-transform3d a-touch-scrolling a-text-shadow a-text-stroke a-box-shadow a-border-radius a-border-image a-opacity a-transform a-transition a-ember&quot;]/body[@class=&quot;a-m-us a-aui_72554-c a-aui_a11y_1_699934-c a-aui_a11y_4_835613-c a-aui_a11y_6_837773-c a-aui_a11y_sr_678508-c a-aui_killswitch_csa_logger_372963-c a-aui_pci_risk_banner_210084-c a-aui_preload_261698-c a-aui_rel_noreferrer_noopener_309527-c a-aui_template_weblab_cache_333406-c a-aui_tnr_v2_180836-c a-meter-animate lock-position&quot;]/div[@id=&quot;hmenu-container&quot;]/div[@id=&quot;hmenu-canvas-background&quot;]/div[@class=&quot;nav-sprite hmenu-close-icon&quot;]</value>
      <webElementGuid>a8849020-385b-49fa-a6e1-0f5a211502cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-canvas-background']/div</value>
      <webElementGuid>2e68fe6e-2fd1-4b67-ab37-08d7d9aca0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>c40f7d87-fa78-45c4-88cf-33e7337f872b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
